---

  - name: Generate en_GB.UTF-8 locale
    shell: locale-gen en_GB.UTF-8

  - name: Update APT package cache
    apt: update_cache=yes
 
  - name: Upgrade APT to the lastest packages
    apt: upgrade=safe

  - include: swap.yml
  - include: harden.yml

  - name: Install base packages
    apt: pkg={{ item }} state=installed
    with_items:
      - fail2ban
      - tmux
      - unattended-upgrades
      - vim
      - zip

  - name: Include tmux config
    copy: src=etc/tmux.conf dest=/etc/tmux.conf

  - name: Make sure unattended-upgrades only installs from $ubuntu_release-security
    lineinfile: dest=/etc/apt/apt.conf.d/50unattended-upgrades regexp="$ubuntu_release-updates" state=absent

  - name: Update sudo group to sudo without a password
    lineinfile: "dest=/etc/sudoers regexp='^%sudo' line='%sudo ALL=NOPASSWD: ALL'"

  - name: Add users
    user: name={{ item.key }} groups={{ item.value.groups }} shell=/bin/bash password="$6$/t7Y696mWgLvg/3$pMWcPJiu.VN8bdmrR0vayCc7fBxGPBCg/L7nTtfHRn19R0fS68wzLVFsiXqhIi42cCdUs9vGfRdD/6xrEfpBI1"
    with_dict: users

  - name: Set users public keys
    authorized_key: user={{ item.key }} key="{{ item.value.key }}"
    with_dict: users

  - name: Update sshd_config
    copy: src=etc/ssh/sshd_config dest=/etc/ssh/sshd_config
    notify:
      - restart sshd

  - name: Open port 22 through ufw
    shell: ufw allow 22/tcp

  - name: Enable ufw
    shell: echo 'y' | ufw enable
 
 
