---

- hosts: all
  sudo: true
  roles:
    - role: common

- hosts: webservers
  sudo: true
  roles:
    - role: postgresql
    - role: nginx
      sites:
        root_redirect: 'root-redirect.conf.j2'
    - role: dokku
      version: 'v0.3.11'
      plugins:
        custom-domains:
          repo: https://github.com/neam/dokku-custom-domains.git
          version: 1.0.1
        dokku-rebuild:
          repo: https://github.com/scottatron/dokku-rebuild.git
          version: c58cbecaa85133538aa7747073f0d82ba4834ac4
        dokku-slack:
          repo: https://github.com/ribot/dokku-slack.git
          version: 767a4c6a4d96d6819a9e51d482f1db83f683d018
          env:
            SLACK_NOTIFY: 1
            SLACK_URL: "{{ slack_url }}"
            SLACK_USERNAME: "dokkubot"
            SLACK_CHANNEL: "infrastructure"
        dokku-pg-plugin:
          repo: https://github.com/beardandcode/dokku-pg-plugin.git
          version: improvements
