---

- hosts: all
  sudo: true
  roles:
    - role: common

- hosts: webservers
  sudo: true
  roles:
    - role: postgresql
    - role: nginx
      sites:
        root_redirect: 'root-redirect.conf.j2'
    - role: dokku
      version: 'v0.3.2'
      plugins:
        custom-domains:
          repo: https://github.com/neam/dokku-custom-domains.git
          version: 1.0.1
        dokku-rebuild:
          repo: https://github.com/scottatron/dokku-rebuild.git
          version: c58cbecaa85133538aa7747073f0d82ba4834ac4
