---

- hosts: all
  sudo: true
  roles:
    - role: common

- hosts: webservers
  sudo: true
  roles:
    - role: postgresql
    - role: nginx
      sites:
        root_redirect: 'root-redirect.conf.j2'
    - role: dokku
      version: 'v0.3.2'
